#pragma once

namespace XIIlib
{
	enum SpriteNum
	{
		DEBUG_TEXT_TEX = 0, DEBUG_JISTEXT_TEX,
		DIGITALNUMBER_TEX, EFEECT1_TEX,
		// ゲームで使ってる部分
		SPACE_TEX, 
		OVER_GO_TITLE,CLEAR_GO_TITLE,
		TEXT_RETRY, TEXT_SELECT,
		GAMEOVER_TEX,BOSSOVER_TEX, 
		STAGEBG1_TEX,
		EASY_BUTTON_TEX, NORMAL_BUTTON_TEX, HARD_BUTTON_TEX,
		EDGE_TEX, 
		TITLEBG_TEX, TITLELOG_TEX,
		GAMECLEAR_TEX, BOSSCLEAR_TEX,
		OPERATORGUIDE_TEX, MENU_TEX,CURSOR_TEX,
		BUTTON_PLAY_TEX,BUTTON_SELECT_TEX,BUTTON_TITLE_TEX,
		BUTTON_PLAYER_TEX,BUTTON_ENEMY_TEX,
		PLAYERGUIDES_TEX, ENEMYGUIDES_TEX,
		BG_TEX,STAGESELECT_TEX,BAN_TEX,
		STORY0_SP,STORY1_SP,STORY2_SP,
		WHITEOUT,
		YANKEE,YANKEE_SILHOUETTE,
		BOSS,BOSS_SILHOUETTE,
		BIKE,BIKE_SILHOUETTE,
		PLAYER1,PLAYER2,
		BLOOD_BACK_GROUND,
		SELECT_BACK_GROUND,
		ZOKU,
		SHITAPPA,
		CLEARCONDITION,
		BOSSCLEARCONDITION,
		TIMER_BAR,
		TIMER_EDGE,
		MOJI_TEN,
		MOJI_TEN2,
		MOJI_BOKU,
		MOJI_HAI ,
		MOJI_KA  ,
		MOJI_KEN ,
		MOJI_TOU ,
		MOJI_TYOU,
		MOJI_ZYOU,
		MOJI_CLEAR1,
		MOJI_CLEAR2,
		MOJI_CLEAR3,
		MOJI_CLEAR4
	};
	class SpriteLoader
	{	
	public:
		static void Load();
	private:
		static unsigned int spriteCount;
	};
}
